### PR TITLE
Dropdown, improve styling on stylist profile component, as well as improve navbar.

### PR DESCRIPTION
**Pull request by punkrockeng**

### CODE REVIEW

**Review by Drewclam — APPROVED** [review]
lgtm

**Comment by akcays** [comment]
Lgtm, just 2 comments:
1. customer-navbar.component.html line 30: can we change 'Message' into 'Messages'?
2. customer-navbar.component.html line 4: I saw router link is removed, couldn't understand why, do we not want it to redirect to home?

**Comment by gitParul** [comment]
lg

**Comment by akcays** [comment]
LG

**Pull request merged**
